### ISSUE TITLE
mdx_unimoji is deprecated

### ISSUE THREAD

**Issue by shmpwk** [autowarefoundation/autoware-github-actions#145]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

mdx_unimoji seems deprecated.
This is because it depends [setuptools-markdown](https://github.com/kernc/mdx_unimoji/blob/master/setup.py#L21) and it is deprecated because of https://github.com/msabramo/setuptools-markdown/pull/21

Related issue
https://zenn.dev/mebiusbox/articles/81d977a72cee01#%F0%9F%93%9D-%E8%A3%9C%E8%B6%B3-(2021%2F1%2F13)

### Expected behavior

mdx_unimoji can be installed

### Actual behavior

mdx_unimoji cannot be installed

### Steps to reproduce

install mdx_unimoji like `pip install mdx_unimoji`

**Comment by kenji-miyake** [comment]
@shmpwk Thank you for reporting this! Let's remove the dependency.
https://github.com/autowarefoundation/autoware/discussions/286#discussioncomment-2727319

**Comment by shmpwk** [comment]
close by https://github.com/autowarefoundation/autoware-github-actions/pull/146
