### ISSUE TITLE
[remove-exec-depend] "-" not parsed in packages name

### ISSUE THREAD

**Issue by ambroise-arm** [autowarefoundation/autoware-github-actions#159]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

The regex here: https://github.com/autowarefoundation/autoware-github-actions/blob/9d8d2d8d1d0380c4a868c67c145051df4dacb048/remove-exec-depend/action.yaml#L9 doesn't match the character "-".
In the case of the autoware.universe repository, it leaves packages such as `libqt5-widgets` or `python3-matplotlib` as exec-depend.

It's not causing any problem at the moment, but it didn't look right.

### Expected behavior

Remove all exec-depend.

### Actual behavior

Some exec-depend are left.

### Steps to reproduce

In autoware.universe, run the action command: 
```sh
find . -name package.xml | xargs -I {} sed -i -rz "s|<exec_depend>\s*[a-zA-Z_0-9]+\s*</exec_depend>\n||g" {}
```
and grep for exec_depend:
```sh
grep -rn "<exec_depend>" $(find . -name package.xml)
```

**Comment by kenji-miyake** [comment]
Thank you for reporting this! :smile: 

I'll link the background information of this action.
https://github.com/autowarefoundation/autoware.universe/issues/184

Since it's mainly to prevent dependency packages from unnecessarily increasing due to `*_launch` packages, as you say, there is no big problem right now.

But it seems easy to fix it, so I'll check it soon.

**Comment by kenji-miyake** [comment]
```bash
$ cd autoware.universe
$ find . -name package.xml | xargs -I {} sed -i -rz "s|<exec_depend>\s*[a-zA-Z0-9_-]+\s*</exec_depend>\n||g" {}
$ grep -rn "<exec_depend>" $(find . -name package.xml)
$ git reset --hard
$ find . -name package.xml | xargs -I {} sed -i -rz "s|<exec_depend>\s*[a-zA-Z0-9_]+\s*</exec_depend>\n||g" {}
$ grep -rn "<exec_depend>" $(find . -name package.xml)
./common/autoware_auto_perception_rviz_plugin/package.xml:20:  <exec_depend>libqt5-widgets</exec_depend>
./launch/tier4_integration_launch/package.xml:14:    <exec_depend>python3-bson</exec_depend>
./launch/tier4_integration_launch/package.xml:15:  <exec_depend>python3-tornado</exec_depend>
./vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/package.xml:28:  <exec_depend>python3-matplotlib</exec_depend>
./vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/package.xml:29:  <exec_depend>python3-pandas</exec_depend>
./vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/package.xml:30:  <exec_depend>python3-scipy</exec_depend>
./system/default_ad_api/package.xml:19:  <exec_depend>python3-flask</exec_depend>
```
