### ISSUE TITLE
Advanced settings for CODEOWNERS

### ISSUE THREAD

**Issue by isamu-takagi** [autowarefoundation/autoware-github-actions#236]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Now CODEOWNERS is generated from package.xml. This is easy to understand, but there were times when I wanted to do something more complex. So I would like to support advanced settings.

New features
- Introduce `codeowners.yaml` that affect descendant directories.
- Introduce group file (I know GitHub supports groups, but this can be managed per repository).

### Purpose

Make it easier to manage codeowners
  - Add codeowners for all packages in a directory (global-codeowner is owner of root directory).
  - Add codeowners group
  - Set codeowners as user name

### Possible approaches

Introduce following setting file (codeowners.yaml).
```yaml
users:
  - "@user-name"
  - "email.address@example.com"
groups:
  - "group-name"
```

If you set the following (with group G is user Y and Z):
```
dir
├── codeowners.yaml (user: X)
├── foo
│   └── package.xml (maintainer: A)
├── bar
│   ├── package.xml (maintainer: B)
│   └── codeowners.yaml (group: G)
└── baz
    ├── package.xml (maintainer: C)
    └── codeowners.yaml (group: G)
```

CODEOWNERS for each package is as follows:
- foo: A, X
- bar: B, X, Y, Z
- baz: C, X, Y, Z

### Definition of done

- [ ] update github action: https://github.com/autowarefoundation/autoware-github-actions/pull/235

**Comment by kenji-miyake** [comment]
@isamu-takagi Thank you for your proposal.
To explain the background, generating CODEOWNERS from `package.xml` has the purpose of encouraging developers to maintain `package.xml` properly.
So basically I wouldn't like to introduce another mechanism unless it's really needed.

Regarding your proposal, I'd like to confirm several things below:
- Does the `CODEOWNERS-manual` feature not work for the use case?
- Considering that now admins can bypass reviews, do you still need your extension?
  - https://github.com/orgs/autowarefoundation/discussions/3060#discussioncomment-5731979

**Comment by isamu-takagi** [comment]
> Considering that now admins can bypass reviews, do you still need your extension?

@kenji-miyake If this removes the global-codeowner then most of the problems are solved.

**Comment by kenji-miyake** [comment]
> @kenji-miyake If this removes the global-codeowner then most of the problems are solved. This was due to the need to register reviewers for packages with only one maintainer.

@isamu-takagi cc @xmfcx Yes, I believe we can remove global-codeowner. But we need wait for a while because there is a minor bug with GitHub's new Ruleset feature.
