### ISSUE TITLE
[build-and-test-pr] Cache not found?

### ISSUE THREAD

**Issue by KeisukeShima** [autowarefoundation/autoware-github-actions#47]
I noticed that the cache of the build was not restored in `clang-tidy` job.
@kenji-miyake Is this a known issue?

![image](https://user-images.githubusercontent.com/19993104/152293930-a1de002a-4a20-4ed9-b6d5-331ab38c6085.png)

https://github.com/autowarefoundation/autoware.universe/runs/5047308661?check_suite_focus=true

**Comment by kenji-miyake** [comment]
@KeisukeShima No, I didn't know that. Could you take a look, please?

**Comment by KeisukeShima** [comment]
Yes, of course. I will investigate this issue.

**Comment by kenji-miyake** [comment]
@KeisukeShima Maybe this? https://github.com/actions/cache/issues/638

**Comment by KeisukeShima** [comment]
@kenji-miyake Thank you! Maybe that is the cause of this problem.
I have created a PR to fix the path.
https://github.com/autowarefoundation/autoware-github-actions/pull/48
