### ISSUE TITLE
[delete-closed-pr-docs] Ignore the version "latest"

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware-github-actions#96]
https://github.com/autowarefoundation/autoware.universe/runs/5457449383?check_suite_focus=true

```sh-session
$ mike list
pr-47
pr-46
pr-45
pr-43
pr-40
pr-28
pr-27
pr-25
pr-24
pr-21
pr-18
pr-17
main [latest]
```

**Comment by kenji-miyake** [comment]
Probably, there are two problems.
1. PR versions are tagged as `latest` like `pr-47 [latest]`.
2. `delete-closed-pr-docs` cannot ignore `[latest]`.

**Comment by kenji-miyake** [comment]
```sh-session
$ echo "pr-47 [latest]" | grep -oP "pr-\w+"
pr-47
```

**Comment by kenji-miyake** [comment]
Also, the PR condition should be ignored here.
https://github.com/autowarefoundation/autoware.universe/blob/e61c02aaedd9c589a8a679597a87b8aca25d6fc7/.github/workflows/deploy-docs.yaml#L41

**Comment by kenji-miyake** [comment]
@KeisukeShima Could you catch up with this and will work on it if possible? :pray:

**Comment by KeisukeShima** [comment]
@kenji-miyake 

> PR versions are tagged as latest like pr-47 [latest].

What is your expected behavior?  I would like to know more about why No. 1 is a problem.

> delete-closed-pr-docs cannot ignore [latest]

How about adding `continue` sequence to [here](https://github.com/autowarefoundation/autoware-github-actions/blob/main/delete-closed-pr-docs/action.yaml#L42)?

```bash
        for docs_version in ${{ steps.get-docs-versions.outputs.docs-versions }}; do
          pr_number=$(echo "$docs_version" | grep -oP "pr-\K([0-9]+)")

         # Added
         if [ not "$pr_number" ]; then
           continue
         fi

          url="https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"

          echo "url: $url"
          state=$(curl -fsSL "$url" -H "Authorization: token ${{ inputs.token }}" | grep -oP '"state": "\K([a-z]+)')

          if [ "$state" = "closed" ]; then
            closed_docs_versions+=("$docs_version")
          fi
        done
```

> Also, the PR condition should be ignored here.

Could you explain that to me in a little more detail? I think this PR condition looks good.

**Comment by kenji-miyake** [comment]
> What is your expected behavior? I would like to know more about why No. 1 is a problem.

@KeisukeShima `latest` should be used only for `main` and should not be for PR branches.

> How about adding continue sequence to here?

No, it's not `pr-47` and `[latest]` but `pr-47 [latest]`.
We have to remove it by https://github.com/autowarefoundation/autoware-github-actions/issues/96#issuecomment-1061292507.

> Could you explain that to me in a little more detail? I think this PR condition looks good.

Like this.

```
latest: ${{ not pull_request(and not pull_request_target) && github.ref_name == github.event.repository.default_branch }}
```

**Comment by KeisukeShima** [comment]
Thanks for your explanation! I understood.

**Comment by KeisukeShima** [comment]
I have created PR to resolve the following issue:

1. PR versions are tagged as latest like pr-47 [latest].
    1. https://github.com/autowarefoundation/autoware-documentation/pull/55
1. delete-closed-pr-docs cannot ignore [latest].
    1. https://github.com/autowarefoundation/autoware-github-actions/pull/104

**Comment by kenji-miyake** [comment]
@KeisukeShima v1.3.2 worked! Thank you. :+1: 
https://github.com/autowarefoundation/autoware.universe/runs/5536446826?check_suite_focus=true

**Comment by KeisukeShima** [comment]
All problems have been resolved. Closing.
